name: hm-pipeline
on: push
jobs:
  code-build:
    runs-on: self-hosted
    steps:
      - name: code-build
        run: build.sh
  docker-build:
    needs: code-build
    runs-on: self-hosted
    steps:
      - name: docker-build
        run: |
          echo $(pwd)
          docker build -t vile-api .
  ecr-push:
    needs: [code-build, docker-build]
    runs-on: self-hosted
    steps:
    - name: ecr-push
      run: echo "Image pushed into ECR"