name: hm-pipeline
on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: code-build
        run: echo "Hello World!"
      - name: docker-build
        run: echo "Docker image built completed"
      - name: ecr-push
        run: echo "Image pushed into ECR"