name: hm-pipeline
on: push
jobs:
  sonar-scanning:
    runs-on: self-hosted
    steps:
      - run: echo "Sonarqube scanning..."
  semgrep:
      runs-on: self-hosted
      steps:
      - run: echo "Semgrep scanning..."
  checkmarx:
      runs-on: self-hosted
      steps:
      - run: echo "Checkmarx scanning..."
  code-build:
    needs: [sonar-scanning, semgrep, checkmarx]
    runs-on: self-hosted
    steps:
      - run: export GIT_SSL_NO_VERIFY=1
      # - run: echo ${{toJson(github)}}
      - run: echo "Last commit SHA $GITHUB_SHA and repo owner name is $GITHUB_REPOSITORY_OWNER"
  docker-build:
    needs: code-build
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v3
      - name: docker-build
        run: |
          ls -lah
  ecr-push:
    needs: [code-build, docker-build]
    runs-on: self-hosted
    steps:
    - name: ecr-push
      run: echo "Image pushed into ECR"
