name: hm-pipeline
on: push
jobs:
  code-build:
    runs-on: self-hosted
    steps:
      - name: code-build
        run: |
          export GIT_SSL_NO_VERIFY=1
          echo ${{toJson(github)}}
  docker-build:
    needs: code-build
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v3
      - name: docker-build
        run: |
          ls -lah
  ecr-push:
    needs: [code-build, docker-build]
    runs-on: self-hosted
    steps:
    - name: ecr-push
      run: echo "Image pushed into ECR"
